"""add ynab token columns

Revision ID: 7c1ab1c042c3
Revises: ff357c8546f0
Create Date: 2025-03-23 12:26:36.266690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c1ab1c042c3"
down_revision: Union[str, None] = "ff357c8546f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ynab_token_expires_at", sa.DateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "ynab_token_created_at", sa.DateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "ynab_token_updated_at", sa.DateTime(timezone=True), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_column("ynab_token_updated_at")
        batch_op.drop_column("ynab_token_created_at")
        batch_op.drop_column("ynab_token_expires_at")
    # ### end Alembic commands ###
