"""drop_notes_table

Revision ID: ff357c8546f0
Revises: 396f999eb4f6
Create Date: 2025-03-17 12:15:40.994489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff357c8546f0"
down_revision: Union[str, None] = "396f999eb4f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column(
            "id", sa.BIGINT(), autoincrement=True, nullable=False, primary_key=True
        ),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="notes_pkey"),
    )
    # ### end Alembic commands ###
